# Kleinanzeigen's Category Tree

| L1 - CATEGORY NAME      | L2 - SUB CATEGORY                | CATEGORY ID | Attributes                                                                                                                                                                                                                                  |
| ----------------------- | -------------------------------- | ----------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| Auto_Rad_Boot           |                                  |             |                                                                                                                                                                                                                                             |
|                         | Anhaenger_Nutzfahrzeuge          | 276         | Agrarfahrzeuge, Anhänger, Baumaschinen, Busse, LKW, Sattelzugmaschinen & Auflieger, Stapler, Nutzfahrzeugteile & Zubehör, Weitere Nutzfahrzeuge & Anhänger                                                                                  |
|                         | Autos                            | 216         |                                                                                                                                                                                                                                             |
|                         | Autoteile_Reifen                 | 223         | Auto Hifi & Navigation, Ersatz- & Reparaturteile, Reifen & Felgen, Tuning & Styling, Werkzeug, Weitere Autoteile                                                                                                                            |
|                         | Boote_Bootszubehoer              | 211         | Motorboote, Segelboote, Kleinboote, Schlauchboote, Jetski, Bootstrailer, Bootsliegeplätze, Bootszubehör, Weitere Boote                                                                                                                      |
|                         | Fahrraeder                       | 217         |                                                                                                                                                                                                                                             |
|                         | Motorraeder_Roller               | 305         | Mofas & Mopeds, Motorräder, Quads, Motorroller & Scooter                                                                                                                                                                                    |
|                         | Motorraeder_Roller_Teile         | 306         | Ersatz- & Reparaturteile, Reifen & Felgen, Motorradbekleidung                                                                                                                                                                               |
|                         | Reparaturen_Dienstleistungen     | 280         |                                                                                                                                                                                                                                             |
|                         | Wohnwagen_Mobile                 | 220         | Alkoven, Integrierter, Kastenwagen, Teilintegrierter, Wohnwagen, Weitere Wohnwagen & -mobile                                                                                                                                                |
|                         | Sonstiges                        | 241         |                                                                                                                                                                                                                                             |
|                         |                                  |             |                                                                                                                                                                                                                                             |
| Eintrittskarten_Tickets |                                  |             |                                                                                                                                                                                                                                             |
|                         | Comedy_Kabarett                  | 254         |                                                                                                                                                                                                                                             |
|                         | Kinder                           | 252         |                                                                                                                                                                                                                                             |
|                         | Klassik_Kultur                   | 251         |                                                                                                                                                                                                                                             |
|                         | Konzerte                         | 255         |                                                                                                                                                                                                                                             |
|                         | Sport                            | 257         |                                                                                                                                                                                                                                             |
|                         | Bahn_OEPNV                       | 286         |                                                                                                                                                                                                                                             |
|                         | Gutscheine                       | 287         |                                                                                                                                                                                                                                             |
|                         | Sonstige                         | 256         |                                                                                                                                                                                                                                             |
|                         |                                  |             |                                                                                                                                                                                                                                             |
|                         |                                  |             |                                                                                                                                                                                                                                             |
| Familie_Kind_Baby       |                                  |             |                                                                                                                                                                                                                                             |
|                         | Altenpflege                      | 236         |                                                                                                                                                                                                                                             |
|                         | Baby_Kinderkleidung              | 22          | Hosen & Jeans, Kleider & Röcke, Shirts & Tops, Hemden, Jacken & Mäntel, Pullover & Strickjacken, Wäsche, Sportbekleidung, Bademode, Accessoires, Kleidungspakete, Weitere Baby- & Kinderkleidung                                            |
|                         | Baby_Kinderschuhe                | 19          | Ballerinas, Halb- & Schnürschuhe, Hausschuhe, Sandalen, Outdoor & Wanderschuhe, Sneaker & Sportschuhe, Stiefel & Stiefeletten, Badeschuhe, Weitere Schuhe                                                                                   |
|                         | Babyausstattung                  | 258         |                                                                                                                                                                                                                                             |
|                         | Babyschalen_Kindersitze          | 21          |                                                                                                                                                                                                                                             |
|                         | Babysitter_Kinderbetreuung       | 237         |                                                                                                                                                                                                                                             |
|                         | Kinderwagen_Buggys               | 25          |                                                                                                                                                                                                                                             |
|                         | Kinderzimmermoebel               | 20          | Betten & Wiegen, Hochstühle & Laufställe, Schränke & Kommoden, Wickeltische & Zubehör, Wippen & Schaukeln, Weitere Kinderzimmermöbel                                                                                                        |
|                         | Spielzeug                        | 23          | Action- & Spielfiguren, Babyspielzeug, Barbie & Co, Dreirad & Co, Gesellschaftsspiele, Holzspielzeug, LEGO & Duplo, Lernspielzeug, Playmobil, Puppen, Spielzeugautos, Spielzeug für draußen, Stofftiere, Weiteres Spielzeug                 |
|                         | Sonstiges                        | 18          |                                                                                                                                                                                                                                             |
|                         |                                  |             |                                                                                                                                                                                                                                             |
| Freizeit_Nachbarschaft  |                                  |             |                                                                                                                                                                                                                                             |
|                         | Esoterik_Spirituelles            | 232         |                                                                                                                                                                                                                                             |
|                         | Essen_Trinken                    | 248         |                                                                                                                                                                                                                                             |
|                         | Freizeitaktivitaeten             | 187         |                                                                                                                                                                                                                                             |
|                         | Handarbeit_Basteln_Kunsthandwerk | 282         |                                                                                                                                                                                                                                             |
|                         | Kuenstler_Musiker                | 191         |                                                                                                                                                                                                                                             |
|                         | Kunst                            | 240         |                                                                                                                                                                                                                                             |
|                         | Modellbau                        | 249         |                                                                                                                                                                                                                                             |
|                         | Reise_Eventservices              | 233         |                                                                                                                                                                                                                                             |
|                         | Sammeln                          | 234         | Ansichts- & Postkarten, Autogramme, Bierkrüge & -gläser, Briefmarken, Comics, Flaggen, Münzen, Porzellan, Puppen & Puppenzubehör, Sammelbilder & Sticker, Sammelkartenspiele, Überraschungseier, Werbeartikel, Weiteres Sammeln             |
|                         | Sport_Camping                    | 230         | Ballsport, Camping & Outdoor, Fitness, Radsport, Tanzen & Laufen, Wassersport, Wintersport, Weiteres Sport & Camping                                                                                                                        |
|                         | Troedel_kistenweise              | 250         |                                                                                                                                                                                                                                             |
|                         | Verloren_Gefunden                | 189         |                                                                                                                                                                                                                                             |
|                         | Sonstiges                        | 242         |                                                                                                                                                                                                                                             |
|                         |                                  |             |                                                                                                                                                                                                                                             |
| Haus_Garten             |                                  |             |                                                                                                                                                                                                                                             |
|                         | Badezimmer                       | 91          |                                                                                                                                                                                                                                             |
|                         | Bueromoebel                      | 93          |                                                                                                                                                                                                                                             |
|                         | Dekoration                       | 246         | Bilder & Poster, Kerzen & Kerzenhalter, Spiegel, Vasen, Weitere Dekoration                                                                                                                                                                  |
|                         | Dienstleistungen_Haus_Garten     | 239         | Bau & Handwerk, Garten- & Landschaftsbau, Haushaltshilfe, Reinigungsservice, Reparaturen, Wohnungsauflösungen, Weitere Dienstleistungen Haus & Garten                                                                                       |
|                         | Garten_Pflanzen                  | 89          | Blumentöpfe, Dekoration, Gartengeräte, Gartenmöbel, Pflanzen, Weiteres Gartenzubehör & Pflanzen                                                                                                                                             |
|                         | Heimtextilien                    | 90          |                                                                                                                                                                                                                                             |
|                         | Heimwerken                       | 84          |                                                                                                                                                                                                                                             |
|                         | Kueche_Esszimmer                 | 86          | Besteck, Geschirr, Gläser, Kleingeräte, Küchenschränke, Stühle, Tische, Weiteres Küche & Esszimmer                                                                                                                                          |
|                         | Lampen_Licht                     | 82          |                                                                                                                                                                                                                                             |
|                         | Schlafzimmer                     | 81          | Betten, Lattenroste, Matratzen, Nachttische, Schränke, Weiteres Schlafzimmer                                                                                                                                                                |
|                         | Wohnzimmer                       | 88          | Regale, Schränke & Schrankwände, Sitzmöbel, Sofas & Sitzgarnituren, Tische, TV & Phonomöbel, Weiteres Wohnzimmer                                                                                                                            |
|                         | Sonstiges                        | 87          |                                                                                                                                                                                                                                             |
|                         |                                  |             |                                                                                                                                                                                                                                             |
| Haustiere               |                                  |             |                                                                                                                                                                                                                                             |
|                         | Fische                           | 138         | Aquariumfische, Barsche, Diskusfische, Garnelen & Krebse, Koi, Schnecken, Wasserpflanzen, Welse, Weitere Fische                                                                                                                             |
|                         | Hunde                            | 134         | Mischlinge, Beagle, Bernhardiner, Border Collie, Boxer, Cocker Spaniel, Collie, Dackel, Dalmatiner, Dobermann, Dogge, Golden Retriever, Husky, Jack Russell Terrier, Labrador, Malteser, Pudel, Schäferhunde, Spitz, Terrier, Weitere Hunde |
|                         | Katzen                           | 136         | Britisch Kurzhaar, Hauskatze, Maine Coon, Perser, Siam, Weitere Katzen                                                                                                                                                                      |
|                         | Kleintiere                       | 132         | Hamster, Hasen & Kaninchen, Mäuse & Ratten, Meerschweinchen, Weitere Kleintiere                                                                                                                                                             |
|                         | Pferde                           | 139         | Großpferde, Kleinpferde & Ponys                                                                                                                                                                                                             |
|                         | Reptilien                        | 244         | Schlangen, Echsen, Spinnen, Weitere Reptilien                                                                                                                                                                                               |
|                         | Tierbetreuung_Training           | 133         |                                                                                                                                                                                                                                             |
|                         | Vermisste_Tiere                  | 283         | Entlaufen, Gefunden                                                                                                                                                                                                                         |
|                         | Vogel                            | 243         |                                                                                                                                                                                                                                             |
|                         | Sonstige                         | 131         |                                                                                                                                                                                                                                             |
|                         | zubehoer                         | 313         | Fische, Hunde, Katzen, Kleintiere, Pferde, Reptilien, Vögel, Weiteres Zubehör Haustiere                                                                                                                                                     |
|                         |                                  |             |                                                                                                                                                                                                                                             |
| Immobilien              |                                  |             |                                                                                                                                                                                                                                             |
|                         | Auf_Zeit_WG                      | 199         |                                                                                                                                                                                                                                             |
|                         | Ferienwohnung_Ferienhaus         | 275         | Kaufen, Mieten                                                                                                                                                                                                                              |
|                         | Garage_Lagerraum                 | 197         | Kaufen, Mieten                                                                                                                                                                                                                              |
|                         | Gewerbeimmobilien                | 277         | Kaufen, Mieten                                                                                                                                                                                                                              |
|                         | Grundstuecke_Garten              | 207         |                                                                                                                                                                                                                                             |
|                         | Haus_kaufen                      | 208         |                                                                                                                                                                                                                                             |
|                         | Haus_mieten                      | 205         |                                                                                                                                                                                                                                             |
|                         | Umzug_Transport                  | 238         |                                                                                                                                                                                                                                             |
|                         | Wohnung_kaufen                   | 196         |                                                                                                                                                                                                                                             |
|                         | Wohnung_mieten                   | 203         |                                                                                                                                                                                                                                             |
|                         | Sonstiges                        | 198         |                                                                                                                                                                                                                                             |
|                         |                                  |             |                                                                                                                                                                                                                                             |
| Jobs                    |                                  |             |                                                                                                                                                                                                                                             |
|                         | Ausbildung                       | 118         |                                                                                                                                                                                                                                             |
|                         | Bau_Handwerk_Produktion          | 111         | Bauhelfer, Dachdecker, Elektriker, Fliesenleger, Maler, Maurer, Produktionshelfer, Schlosser, Tischler, Weitere Berufe                                                                                                                      |
|                         | Bueroarbeit_Verwaltung           | 114         | Buchhalter, Bürokauffrau/-mann, Sachbearbeiter/-in, Sekretärin, Weitere Berufe                                                                                                                                                              |
|                         | Gastronomie_Tourismus            | 110         | Barkeeper, Hotelfachfrau/-mann, Kellner/-in, Koch/Köchin, Küchenhilfe, Servicekraft, Zimmermädchen, Weitere Berufe                                                                                                                          |
|                         | Heimarbeit_Mini_Nebenjobs        | 107         |                                                                                                                                                                                                                                             |
|                         | Kundenservice_Callcenter         | 105         |                                                                                                                                                                                                                                             |
|                         | Praktika                         | 125         |                                                                                                                                                                                                                                             |
|                         | Sozialer_Sektor_Pflege           | 123         | Altenpfleger/-in, Arzthelferin, Erzieher/-in, Krankenschwester/ Krankenpfleger, Physiotherapeut/-in, Weitere Berufe                                                                                                                         |
|                         | Transport_Logistik_Verkehr       | 247         | Kraftfahrer, Kurierfahrer, Lagerhelfer, Staplerfahrer, Weitere Berufe                                                                                                                                                                       |
|                         | Vertrieb_Einkauf_Verkauf         | 117         | Buchhalter/-in, Immobilienmakler, Kaufmann/-frau, Verkäufer/-in, Weitere Berufe                                                                                                                                                             |
|                         | Sonstige_Berufe                  | 109         | Designer/Grafiker, Friseur/-in, Haushaltshilfe, Hausmeister, Reinigungskraft, Weitere Berufe                                                                                                                                                |
|                         |                                  |             |                                                                                                                                                                                                                                             |
| Mode_Beauty             |                                  |             |                                                                                                                                                                                                                                             |
|                         | Accessoires_Schmuck              | 156         | Mützen, Schals & Handschuhe, Schmuck, Sonnenbrillen, Taschen & Rucksäcke, Uhren, Weitere Accessoires & Schmuck                                                                                                                              |
|                         | Beauty_Gesundheit                | 224         | Make-Up & Gesichtspflege, Haarpflege, Körperpflege, Hand- & Nagelpflege, Gesundheit, Weiteres Beauty & Gesundheit                                                                                                                           |
|                         | Kleidung_Damen                   | 154         | Hemden & Blusen, Hosen, Jacken & Mäntel, Pullover, Röcke & Kleider, Shirts & Tops, Umstandsmode, Weitere Damenbekleidung                                                                                                                    |
|                         | Kleidung_Herren                  | 160         | Hemden, Hosen, Jacken & Mäntel, Pullover, Shirts, Weitere Herrenbekleidung                                                                                                                                                                  |
|                         | Schuhe_Damen                     | 159         | Ballerinas, Halb- & Schnürschuhe, Hausschuhe, Outdoor & Wanderschuhe, Pumps & High Heels, Sandalen, Sneaker & Sportschuhe, Stiefel & Stiefeletten, Weitere Schuhe                                                                           |
|                         | Schuhe_Herren                    | 158         | Halb- & Schnürschuhe, Hausschuhe, Sandalen, Sneaker & Sportschuhe, Stiefel & Stiefeletten, Outdoor & Wanderschuhe, Weitere Schuhe                                                                                                           |
|                         | Sonstiges                        | 155         |                                                                                                                                                                                                                                             |
|                         |                                  |             |                                                                                                                                                                                                                                             |
| Multimedia_Elektronik   |                                  |             |                                                                                                                                                                                                                                             |
|                         | Audio_Hifi                       | 172         | CD Player, Lautsprecher & Kopfhörer, MP3 Player, Radio & Receiver, Stereoanlagen, Weiteres Audio & Hifi                                                                                                                                     |
|                         | Dienstleistungen_EDV             | 226         |                                                                                                                                                                                                                                             |
|                         | Foto                             | 245         | Kamera, Objektiv, Zubehör, Kamera & Zubehör, Weiteres Foto                                                                                                                                                                                  |
|                         | Handy_Telekom                    | 173         | Apple, HTC, LG, Motorola, Nokia, Samsung, Siemens, Sony, Faxgeräte, Telefone, Weitere Handys & Telefone                                                                                                                                     |
|                         | Haushaltsgeraete                 | 176         | Haushaltskleingeräte, Herde & Backöfen, Kaffee- & Espressomaschinen, Kühlschränke & Gefriergeräte, Spülmaschinen, Staubsauger, Waschmaschinen & Trockner, Weitere Haushaltsgeräte                                                           |
|                         | Konsolen                         | 279         | Pocket Konsolen, PlayStation, Xbox, Wii, Weitere Konsolen                                                                                                                                                                                   |
|                         | Notebooks                        | 278         |                                                                                                                                                                                                                                             |
|                         | PC_Videospiele                   | 227         | DS, Nintendo Spiele, PlayStation Spiele, Xbox Spiele, Wii Spiele, PC Spiele, Weitere Videospiele                                                                                                                                            |
|                         | PC_Zubehoer_Software             | 225         | Drucker & Scanner, Festplatten & Laufwerke, Gehäuse, Grafikkarten, Kabel & Adapter, Mainboards, Monitore, Multimedia, Netzwerk & Modem, Prozessoren / CPUs, Speicher, Software, Tastatur & Maus, Weiteres PC-Zubehör                        |
|                         | PCs                              | 228         |                                                                                                                                                                                                                                             |
|                         | TV_Video                         | 175         | DVD-Player & Recorder, Fernseher, TV-Receiver, Weitere TV & Video                                                                                                                                                                           |
|                         | Tablets_reader                   | 285         | iPad, Kindle, Samsung Tablets, Weitere Tablets & Reader                                                                                                                                                                                     |
|                         | Sonstiges                        | 168         |                                                                                                                                                                                                                                             |
|                         |                                  |             |                                                                                                                                                                                                                                             |
| Musik_Film_Buecher      |                                  |             |                                                                                                                                                                                                                                             |
|                         | Buecher_Zeitschriften            | 76          | Antiquarische Bücher, Kinderbücher, Krimis & Thriller, Kunst & Kultur, Sachbücher, Science Fiction, Unterhaltungsliteratur, Zeitgenössische Literatur & Klassiker, Zeitschriften, Weitere Bücher & Zeitschriften                            |
|                         | Buero_Schreibwaren               | 281         |                                                                                                                                                                                                                                             |
|                         | Comics                           | 284         |                                                                                                                                                                                                                                             |
|                         | Fachbuecher_Schule_Studium       | 77          |                                                                                                                                                                                                                                             |
|                         | Film_DVD                         | 79          |                                                                                                                                                                                                                                             |
|                         | Musik_CDs                        | 78          |                                                                                                                                                                                                                                             |
|                         | Musikinstrumente                 | 74          |                                                                                                                                                                                                                                             |
|                         | Sonstiges                        | 75          |                                                                                                                                                                                                                                             |
|                         |                                  |             |                                                                                                                                                                                                                                             |
| Unterricht_Kurse        |                                  |             |                                                                                                                                                                                                                                             |
|                         | Beauty & Gesundheit              | 269         |                                                                                                                                                                                                                                             |
|                         | Computerkurse                    | 260         |                                                                                                                                                                                                                                             |
|                         | Esoterik_Spirituelles            | 265         |                                                                                                                                                                                                                                             |
|                         | Kochen_Backen                    | 263         |                                                                                                                                                                                                                                             |
|                         | Kunst_Gestaltung                 | 264         |                                                                                                                                                                                                                                             |
|                         | Musik_Gesang                     | 262         |                                                                                                                                                                                                                                             |
|                         | Nachhilfe                        | 268         |                                                                                                                                                                                                                                             |
|                         | Sportkurse                       | 261         |                                                                                                                                                                                                                                             |
|                         | Sprachkurse                      | 271         |                                                                                                                                                                                                                                             |
|                         | Tanzkurse                        | 267         |                                                                                                                                                                                                                                             |
|                         | Weiterbildung                    | 266         |                                                                                                                                                                                                                                             |
|                         | Sonstige                         | 270         |                                                                                                                                                                                                                                             |
|                         |                                  |             |                                                                                                                                                                                                                                             |
| Zu_verschenken_Tauschen |                                  |             |                                                                                                                                                                                                                                             |
|                         | Tauschen                         | 273         |                                                                                                                                                                                                                                             |
|                         | Verleihen                        | 274         |                                                                                                                                                                                                                                             |
|                         | Zu_verschenken                   | 192         |                                                                                                                                                                                                                                             |
|                         |                                  |             |                                                                                                                                                                                                                                             |
| Dienstleistungen        |                                  |             |                                                                                                                                                                                                                                             |
|                         | Altenpflege                      | 288         |                                                                                                                                                                                                                                             |
|                         | Auto_Rad_Boot                    | 289         |                                                                                                                                                                                                                                             |
|                         | Babysitter_Kinderbetreuung       | 290         |                                                                                                                                                                                                                                             |
|                         | Haus_Garten                      | 291         | Bau & Handwerk, Garten- & Landschaftsbau, Haushaltshilfe, Reinigungsservice, Reparaturen, Wohnungsauflösungen, Weitere Dienstleistungen Haus & Garten                                                                                       |
|                         | Kuenstler_Musiker                | 292         |                                                                                                                                                                                                                                             |
|                         | Multimedia_Elektronik            | 293         |                                                                                                                                                                                                                                             |
|                         | Reise_Event                      | 294         |                                                                                                                                                                                                                                             |
|                         | Tierbetreuung_Training           | 295         |                                                                                                                                                                                                                                             |
|                         | Umzug_Transport                  | 296         |                                                                                                                                                                                                                                             |
|                         | Sonstige                         | 298         |                                                                                                                                                                                                                                             |
